# Generated by Django 2.2 on 2020-08-13 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0002_auto_20200813_1759'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trabajador',
        ),
    ]
