# Generated by Django 2.2 on 2020-08-14 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='calificacion_sentinel',
            field=models.IntegerField(choices=[(0, 'SOLICITADO'), (1, 'APROBADO'), (-1, 'RECHAZADO')]),
        ),
        migrations.AlterField(
            model_name='credito',
            name='estado',
            field=models.IntegerField(choices=[(0, 'SOLICITADO'), (1, 'APROBADO'), (-1, 'RECHAZADO')]),
        ),
    ]
