# Generated by Django 2.2 on 2020-08-14 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0002_auto_20200813_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='calificacion_sentinel',
            field=models.IntegerField(choices=[(1, 'BUENO'), (0, 'REGULAR'), (-1, 'MALO')]),
        ),
    ]
