# Generated by Django 2.2 on 2020-08-14 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0003_auto_20200813_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='calificacion_sentinel',
            field=models.IntegerField(blank=True, choices=[(1, 'BUENO'), (0, 'REGULAR'), (-1, 'MALO')], null=True),
        ),
        migrations.AlterField(
            model_name='credito',
            name='deuda_sbs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='credito',
            name='prediccion_ia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
